# î‚²  ï‰” îƒ† îƒ‡ 
add_newline = true

[line_break]
disabled = true

[character]
#disabled = true
#style = "fg:#ebdbb2"
success_symbol = ""
error_symbol = ""
vicmd_symbol = "î‚±"

[directory]
#disabled = true
style = "fg:#B8BB26"
format = "[$read_only ]($style)[$path ]($style)(fg:#504945)"
read_only="ğŸ”’"
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[hostname]
disabled = true
style = "fg:#ebdbb2"
ssh_only = false
trim_at = ".local"

[username]
disabled = true
style_user = "fg:#ebdbb2"
style_root = "fg:#fb4934"
format = "[ $user]($style)"
show_always = true

[cmd_duration]
disabled = true
style = "fg:#ebdbb2"
format = "[î‚²](fg:#504945)[ï‰” ]($style)[$duration]($style)[fg:#504945)"
show_notifications = true
min_time_to_notify = "9999"

[time]
disabled = true
style = "fg:#ebdbb2"
format = "[î‚²](fg:#504945)[ï€— ]($style)[$time]($style)[fg:#504945)"
time_format = "%T"
utc_time_offset = "1"
time_range = "00:00:00-06:00:00"

[memory_usage]
disabled = true
style = "fg:#ebdbb2"
format = "[î‚²](fg:#504945)[$symbol]($style)[${ram}( | ${swap}) ]($style)[fg:#504945)"
symbol = " ï‚€ "
threshold = 0

[battery]
disabled = true
style = "fg:#ebdbb2"
unknown_symbol = " ï– "
empty_symbol = " ï– "
discharging_symbol = " ï•½ "
charging_symbol = " ï–ƒ "
full_symbol = " ï•¸ "
        [[battery.display]]
        threshold = 10
        style = "bold fg:#fb4934"

        [[battery.display]]
        threshold = 30
        style = "fg:#fe8019"

        [[battery.display]]
        threshold = 50
        style = "fg:#fabd2f"

        

# VCS
[git_branch]
#disabled = true
symbol = "ï˜ "
style = "fg:#FABD2F"

[git_commit]
#disabled = true
style = "fg:#B16286"

[git_state]
#disabled = true
style = "fg:#B16286"
am = "APPLYING-MAILBOX"
am_or_rebase = "APPLYING-MAILBOX/REBASE"

[git_status]
#disabled = true
style = "fg:#B16286"
format = "($conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind)"
conflicted = "(fg:#504945)[Conflicted:${count}î€‰ï‘€](fg:#FB4934)"
staged = "(fg:#504945)[Staged:${count} ](fg:#D3869B)"
modified = "(fg:#504945)[Modified:${count} ](fg:#d65d0e)"
renamed = "(fg:#504945)[Renamed:${count} ](fg:#8EC07C)"
deleted = "(fg:#504945)[Deleted:${count} ](fg:#FB4934)"
untracked = "(fg:#504945)[Untracked:${count} ](fg:#83A598)"
stashed = "(fg:#504945)[Stashed:${count} ](fg:#83A598)"
ahead = "(fg:#504945)[Ahead:${count}â†‘ ](fg:#504945)"
behind = "(fg:#504945)[Behind:${count}â†“ ](fg:#504945)"
diverged = "(fg:#504945)[Diverged:${count}ï­€][ Ahead:${ahead_count}â†‘[ Behind:${behind_count}â†“](fg:#504945)"

[shlvl]
disabled = false
style = "fg:#ebdbb2"
format = "($style)"
symbol = "ï„  "

[env_var]
disabled = true
style = "fg:#ebdbb2"
format = " gambling with [$env_value]($style)"
variable = "GAMBLE_TEST_COMMAND"

[aws]
disabled = true
style = "fg:#ebdbb2"
format = "($style)"
symbol = "îŒ½ "

[conda]
disabled = true
style = "fg:#ebdbb2"
format = "($style)"
symbol = "ï„Œ "

[dart]
disabled = true
style = "fg:#ebdbb2"
format = "($style)"
symbol = "î˜ "

[elixir]
disabled = true
style = "fg:#ebdbb2"
format = "($style)"
symbol = "î‰µ "

[elm]
disabled = true
style = "fg:#ebdbb2"
format = "($style)"
symbol = "î˜¬ "

[golang]
disabled = true
style = "fg:#ebdbb2"
format = "($style)"
symbol = "î˜§ "

[java]
disabled = true
style = "fg:#ebdbb2"
format = "($style)"
symbol = "î‰– "

[nix_shell]
disabled = true
style = "fg:#ebdbb2"
format = "($style)"
symbol = "ïŒ“ "

[nodejs]
disabled = true
style = "fg:#ebdbb2"
format = "($style)[î‚²](fg:#504945)[$symbol$version]($style)[fg:#504945)"
symbol = "ï¢˜ "

[package]
disabled = true
style = "fg:#ebdbb2"
format = "($style)[î‚²](fg:#504945)[$symbol$version]($style)[fg:#504945)"

[php]
disabled = true
style = "fg:#ebdbb2"
format = "($style)"
symbol = "î˜ˆ "

[python]
disabled = true
style = "fg:#ebdbb2"
format = "($style)[î‚²](fg:#504945)[${symbol}${pyenv_prefix}${version}($virtualenv)]($style)[fg:#504945)"
symbol = "î˜† "

[lua]
disabled = true
style = "fg:#ebdbb2"
format = "($style)[î‚²](fg:#504945)[${symbol}${version}]($style)[fg:#504945)"
symbol = "ï†† "

[ruby]
disabled = true
style = "fg:#ebdbb2"
format = "($style)"
symbol = "î‘ "

[rust]
disabled = true
style = "fg:#ebdbb2"
format = "($style)"
symbol = " î¨ "


